server:
  port: 9090

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/
  server:
    wait-time-in-ms-when-sync-empty: 3000

---        
spring:
  boot:
    admin:
      client:
        url: http://localhost:8089
        username: admin
        password: admin
        
--- 
management:
  endpoints:
    web:  
      exposure:
        include: '*'
