server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9091/eureka
  server:
    wait-time-in-ms-when-sync-empty: 3000
       
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: access_control
      uri=mongodb://localhost/access_control
 
  main:
    allow-bean-definition-overriding: true
  application:
    name: delivery-irko-access-control
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
