server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
       
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: access_control
      uri=mongodb://localhost/access_control
 
  main:
    allow-bean-definition-overriding: true
  application:
    name: delivery-irko-access-control
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
